### ISSUE TITLE
Spotify Client Download Link

### ISSUE THREAD

**Issue by abazad** [meik97/SpotiHole#2]
if you want to try this repo, you need old verison spotify.
you can download direct via spotify server.

[https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.42.622.gbd112320-40.exe](https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.42.622.gbd112320-40.exe)

**Comment by meik97** [comment]
Yes, a more detailed installation is provided in the discord server including the correct spotify version.
