### ISSUE TITLE
x spot ify talk

### ISSUE THREAD

**Issue by exislow** [meik97/SpotiHole#3]
del

**Comment by meik97** [comment]
Hi exislow, 

das Ganze ist zwar schon ein Weilchen her aber wir können uns gerne über XSpotify unterhalten.
Ich werde dir bei deinem Vorhaben, aus offensichtlichen Gründen, leider nicht helfen können.
Spotify wird bei solchen Sachen ganz schnell aufmerksam und fackelt nicht lange herum.

Für Fragen kannst du aber trotzdem gerne auf meinen Discord-Server kommen (https://discord.gg/xUyxHesCGj)
